"""
models.py
=========
Typed data structures shared across the application.

`DiligenceInput` mirrors the intake form exactly (one field per question in
the brief). `RiskIssue` is the structured output produced by the risk engine
for each compliance flag raised — it deliberately carries every element a
junior associate would expect to find in a diligence memo entry (issue,
regulation, "why an acquirer should care", consequences, documents,
management questions and SPA protections).
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import List


# ---------------------------------------------------------------------------
# INTAKE FORM INPUT
# ---------------------------------------------------------------------------
@dataclass
class DiligenceInput:
    """All data captured from the diligence intake form."""

    # --- Company profile ----------------------------------------------------
    company_name: str = ""
    industry: str = ""
    exporter: bool = False
    importer: bool = False
    software_exporter: bool = False
    service_exporter: bool = False
    merchanting_trader: bool = False
    sez_unit: bool = False
    eou: bool = False
    annual_turnover_cr: float = 0.0      # INR crore
    export_turnover_cr: float = 0.0      # INR crore
    import_turnover_cr: float = 0.0      # INR crore

    # --- Export compliance -----------------------------------------------------
    outstanding_export_receivables: bool = False
    amount_outstanding_cr: float = 0.0
    num_invoices_outstanding: int = 0
    max_delay_months: float = 0.0
    export_proceeds_realised_within_fema_timelines: bool = True
    ad_extensions_obtained: bool = False
    export_value_reduced_written_off: bool = False
    set_off_arrangements_used: bool = False
    third_party_receipts: bool = False
    exports_invoiced_in_inr: bool = False
    warehouse_exports: bool = False
    project_exports: bool = False
    advance_export_receipts: bool = False

    # --- Import compliance ------------------------------------------------------
    outstanding_import_payables: bool = False
    import_max_delay_months: float = 0.0
    advance_import_payments: bool = False
    imports_not_materialised: bool = False
    advance_payments_repatriated: bool = True
    gold_silver_imports: bool = False
    third_party_payments: bool = False
    reduced_value_settlements: bool = False

    # --- Merchanting trade --------------------------------------------------
    merchanting_trade_conducted: bool = False
    both_legs_completed: bool = True
    within_six_months: bool = True
    mtt_third_party: bool = False
    mtt_supporting_documents_available: bool = True

    # --- Reporting & documentation -------------------------------------------
    edpms_reconciled: bool = True
    idpms_reconciled: bool = True
    outstanding_entries: bool = False
    missing_edfs: bool = False
    supporting_documentation_available: bool = True
    ad_bank_queries_pending: bool = False

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "DiligenceInput":
        # Ignore unknown keys so older sample-data dicts remain compatible.
        valid_keys = {f for f in cls.__dataclass_fields__}
        return cls(**{k: v for k, v in data.items() if k in valid_keys})


# ---------------------------------------------------------------------------
# RISK ISSUE OUTPUT
# ---------------------------------------------------------------------------
@dataclass
class RiskIssue:
    """A single diligence flag generated by the risk engine."""

    issue_id: str
    title: str
    severity: str                       # "Low" | "Medium" | "High" | "Critical" | "Informational"
    score_points: int                   # contribution to the overall 0-100 score
    regulations: List[str]              # e.g. ["Regulation 5", "Regulation 13"]
    heatmap_categories: List[str]       # one or more of config.HEATMAP_CATEGORIES

    explanation: str                    # plain description of the underlying fact pattern
    why_it_matters: List[str]           # bullet points — the M&A lens
    potential_consequences: List[str]
    documents_to_review: List[str]
    management_questions: List[str]
    spa_protections: List[str]

    transaction_impact_label: str       # e.g. "Disclosure Schedule Item"
    transaction_impact_detail: str

    @property
    def is_informational(self) -> bool:
        return self.severity == "Informational"


# ---------------------------------------------------------------------------
# ANALYSIS RESULT (top-level container returned by the risk engine)
# ---------------------------------------------------------------------------
@dataclass
class AnalysisResult:
    total_score: int
    risk_category: str
    risk_color_key: str
    issues: List[RiskIssue] = field(default_factory=list)
    heatmap: dict = field(default_factory=dict)  # category -> {"points": int, "status": str}

    @property
    def scored_issues(self) -> List[RiskIssue]:
        """Issues that actually contribute to the score, ordered by severity."""
        return sorted(
            [i for i in self.issues if not i.is_informational],
            key=lambda i: i.score_points,
            reverse=True,
        )

    @property
    def informational_notes(self) -> List[RiskIssue]:
        return [i for i in self.issues if i.is_informational]

    def top_concerns(self, n: int = 5) -> List[RiskIssue]:
        return self.scored_issues[:n]
