"""
regulations_kb.py
==================
A structured knowledge base summarising the operative provisions of the
Foreign Exchange Management (Export and Import of Goods and Services)
Regulations, 2026 (FEMA 23(R)/2026-RB, dated 13 January 2026, effective
1 October 2026).

This module exists so that every issue generated by the risk engine can cite
its statutory basis precisely, and so the "Applicable FEMA Regulations"
section of the dashboard / executive summary can render a short, accurate
description without hard-coding regulation text inline in the content
library.

NOTE: Summaries are deliberately concise paraphrases for quick reference in
a diligence workflow. They are NOT a substitute for the text of the
Regulations themselves, which should always be reviewed directly for the
purposes of any actual transaction.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RegulationSummary:
    number: str          # e.g. "Regulation 5"
    title: str
    summary: str


REGULATIONS: dict[str, RegulationSummary] = {
    "reg_2": RegulationSummary(
        number="Regulation 2",
        title="Definitions — Specified Authority",
        summary=(
            "Defines the 'specified authority' to which export declarations "
            "and related approvals must be made. For SEZ units, the "
            "specified authority for goods, services and software alike is "
            "the Development Commissioner of the relevant SEZ — distinct "
            "from the Commissioner of Customs, AD Bank or STPI, which are "
            "the relevant authorities for DTA units."
        ),
    ),
    "reg_3": RegulationSummary(
        number="Regulation 3",
        title="Declaration of Exports (EDF)",
        summary=(
            "Requires every exporter of goods or services to file an Export "
            "Declaration Form (EDF). For goods, the EDF is filed at the time "
            "of export (and is deemed filed via the shipping bill at EDI "
            "ports). For services, the EDF must be filed within 30 days "
            "from the end of the month in which the invoice is raised — "
            "except that exporters of services other than software may "
            "instead file on or before receipt of payment. Software "
            "exporters therefore have no such carve-out and must meet the "
            "30-day timeline strictly."
        ),
    ),
    "reg_4": RegulationSummary(
        number="Regulation 4",
        title="Manner of Receipt and Payment / EDPMS-IDPMS Updation",
        summary=(
            "An AD Bank may credit or debit an exporter's / importer's "
            "account only after satisfying itself of the genuineness of the "
            "transaction, and must simultaneously update the corresponding "
            "EDPMS or IDPMS entry. Small-value shipping bills / invoices "
            "(up to ₹10 lakh) may be closed on the basis of a self-"
            "declaration, including on a quarterly bulk basis."
        ),
    ),
    "reg_5": RegulationSummary(
        number="Regulation 5",
        title="Time Period for Realisation of Export Proceeds",
        summary=(
            "Export proceeds (or reduced export value, or set-off amounts) "
            "must be realised and repatriated within 15 months from the "
            "date of shipment (goods) / date of invoice (services), or "
            "within 15 months from the date of sale for warehouse exports. "
            "Where invoicing/settlement is in INR, the period extends to 18 "
            "months. Project exports follow the payment terms of the "
            "underlying contract. The AD Bank may extend the period on a "
            "reasoned request, and must otherwise monitor and follow up on "
            "realisation."
        ),
    ),
    "reg_6": RegulationSummary(
        number="Regulation 6",
        title="Reduction in Export Realisation",
        summary=(
            "The AD Bank may permit reduction (including non-realisation) "
            "of export value on a reasoned request from the exporter, "
            "provided it is satisfied with the justification. For "
            "shipping bills / invoices up to ₹10 lakh, reduction may be "
            "permitted on the basis of a self-declaration alone."
        ),
    ),
    "reg_7": RegulationSummary(
        number="Regulation 7",
        title="Set-off of Export Receivables Against Import Payables",
        summary=(
            "The AD Bank may permit set-off of export receivables against "
            "import payables to/from the same overseas counterparty (or its "
            "group/associate companies), provided this occurs within the "
            "stipulated (or AD-extended) realisation period for the export "
            "proceeds."
        ),
    ),
    "reg_8": RegulationSummary(
        number="Regulation 8",
        title="Third-Party Receipts and Payments",
        summary=(
            "The AD Bank may permit receipts or payments involving a party "
            "other than the contractual exporter/importer/buyer/supplier, "
            "provided it is satisfied as to the bona fides of the "
            "transaction. Such arrangements are permissible but require "
            "AD-level comfort and supporting documentation establishing the "
            "underlying commercial relationship."
        ),
    ),
    "reg_9": RegulationSummary(
        number="Regulation 9",
        title="Time Period for Import Payment",
        summary=(
            "The AD Bank must monitor IDPMS entries and follow up with the "
            "importer to ensure payment within the period specified in the "
            "underlying contract, with extensions available on a reasoned "
            "request."
        ),
    ),
    "reg_10": RegulationSummary(
        number="Regulation 10",
        title="Advance Payments for Exports / Imports; Delayed Import Payments",
        summary=(
            "Advance receipts for exports (and any subsequent realisation) "
            "must generally be routed through the same AD Bank, as must "
            "advance payments for imports and subsequent payments — unless "
            "both ADs are notified of a change. AD Banks may permit advance "
            "import remittances after satisfying themselves of the "
            "genuineness of the requirement, and may require a standby "
            "Letter of Credit / guarantee above specified thresholds. "
            "Interest on advance/delayed payments must not exceed the "
            "all-in-cost ceiling under the Borrowing and Lending Regulations."
        ),
    ),
    "reg_11": RegulationSummary(
        number="Regulation 11",
        title="Import of Gold and Silver — No Advance Remittance",
        summary=(
            "Notwithstanding any other provision of these Regulations, no "
            "advance remittance may be permitted by an AD Bank for the "
            "import of gold or silver. This is an absolute prohibition, not "
            "merely a documentation requirement."
        ),
    ),
    "reg_12": RegulationSummary(
        number="Regulation 12",
        title="Import Not Materialised",
        summary=(
            "Where an import does not materialise within the contract "
            "period (or AD-extended period), the importer must repatriate "
            "any advance payment made. If the advance is not repatriated "
            "(and the IDPMS entry is not marked off), any future advance "
            "import payment by that importer requires an unconditional, "
            "irrevocable standby Letter of Credit or guarantee from an "
            "international bank of repute, or an AD Bank guarantee "
            "counter-guaranteed by such an international bank."
        ),
    ),
    "reg_13": RegulationSummary(
        number="Regulation 13",
        title="Unrealised Exports",
        summary=(
            "If export proceeds remain unrealised for a period beyond one "
            "year from the due date of realisation (or AD-extended due "
            "date), the exporter may undertake further exports only against "
            "receipt of full advance payment or an irrevocable Letter of "
            "Credit. This operates as a forward-looking restriction on the "
            "exporter's trading terms, not merely a reporting flag."
        ),
    ),
    "reg_15": RegulationSummary(
        number="Regulation 15",
        title="Project Exports",
        summary=(
            "The AD Bank may permit receipts/payments for project exports "
            "in accordance with the underlying contract, after satisfying "
            "itself of the genuineness of the project. Temporary cash "
            "surpluses generated outside India from such exports may, "
            "subject to AD monitoring, be deployed in short-term "
            "instruments abroad (maturity of one year or less)."
        ),
    ),
    "reg_16": RegulationSummary(
        number="Regulation 16",
        title="Merchanting Trade Transactions (MTT)",
        summary=(
            "A person undertaking merchanting trade must ensure: (a) the gap "
            "between the outward and inward remittance (or vice versa) does "
            "not exceed six months, subject to AD-approved extension; (b) "
            "outward remittances go only to the overseas seller and inward "
            "remittances are received only from the overseas buyer, subject "
            "to AD-approved third-party exceptions; and (c) documents "
            "evidencing the genuineness of the MTT are provided to the AD "
            "Bank. The AD Bank must monitor both legs to completion and "
            "update EDPMS/IDPMS accordingly."
        ),
    ),
    "reg_17": RegulationSummary(
        number="Regulation 17",
        title="Invoicing and Settlement in INR",
        summary=(
            "Cross-border trade may be invoiced and/or settled in Indian "
            "Rupees in accordance with RBI's broad framework and "
            "instructions issued from time to time. Where this option is "
            "used, the realisation period under Regulation 5 extends to 18 "
            "months."
        ),
    ),
    "reg_18": RegulationSummary(
        number="Regulation 18",
        title="Reporting — EDPMS / IDPMS / FETERS",
        summary=(
            "AD Banks must enter EDF and import details in EDPMS/IDPMS "
            "within five working days of receipt, record all inward/outward "
            "remittances (including for MTT), monitor entries for closure, "
            "and mark off entries once realisation/payment is confirmed. "
            "Specific closure routes exist for advances where no "
            "export/import eventuates and refund/repatriation is not "
            "possible, and for imports settled at reduced value — each "
            "requiring the AD Bank to be satisfied of genuineness. All "
            "foreign trade transactions must also be reported in FETERS."
        ),
    ),
    "reg_19": RegulationSummary(
        number="Regulation 19",
        title="AD Internal Policy and SOP",
        summary=(
            "AD Banks must maintain a documented internal policy and SOP "
            "covering timelines, extensions, adjustments to export "
            "realisation, advance receipts/payments, delegation of "
            "approval authority, an escalation/appeal mechanism for "
            "customer grievances, and proportional charging — disclosed on "
            "the AD's website. While this obligation sits with the AD Bank "
            "rather than the target, it informs how readily the target's AD "
            "is likely to grant extensions, approve set-offs, or close "
            "advance entries — relevant context for assessing the "
            "feasibility of remedial steps identified in diligence."
        ),
    ),
}


def get_regulation(key: str) -> RegulationSummary:
    return REGULATIONS[key]


def format_regulation_list(keys: list[str]) -> list[str]:
    """Return ['Regulation 5 — Time Period for Realisation of Export Proceeds', ...]"""
    out = []
    for k in keys:
        reg = REGULATIONS.get(k)
        if reg:
            out.append(f"{reg.number} — {reg.title}")
        else:
            out.append(k)
    return out
